projectConfigurations:
  browser:
    name: chrome
    baseUrl: https://www.google.com/
    demoUrl: http://www.demoshop24.com/
  credentials:
    password: Shivani@100
  reporting:
    reportConfigPath: /Users/vigneshram/Documents/TestAutomationAccenture/Team-2/target/classes/core/config/extent-config.xml
